### PR TITLE
Add Web Demo & Docker environment 

### PR DESCRIPTION
**Pull request by chenxwh**
This pull request makes it possible to run your model inside a Docker environment, which makes it easier for other people to run it.  We're using an open source tool called [Cog](https://github.com/replicate/cog) to make this process easier.

This also means we can make a web page where other people can try out your model! We have implemented Image Denoising, Deblurring, Dehazing, Deraining and Enhancement in one demo, view it here: https://replicate.com/google-research/maxim. You can find the docker file under the tab ‘run model with docker’. 

We have added some examples to the page, but do claim the page so you can own the page, customise the [Example](https://replicate.com/google-research/maxim/examples) gallery as you like, push any future update to the web demo, and we'll feature it on our website and tweet about it too. You can find the 'Claim this model' button on the top of the page. Any member of the google-research organisation on GitHub can claim the model ~ 

In case you're wondering who I am, I'm from [Replicate](https://replicate.com/home), where we're trying to make machine learning reproducible. We got frustrated that we couldn't run all the really interesting ML work being done. So, we're going round implementing models we like. 😊

### CODE REVIEW

**Comment by vztu** [comment]
Hi @chenxwh, thanks a lot for helping us create these useful tools for easier usage! I have checked the web demo and find it looks super awesome! 

I have just one minor request -- I simply tweaked with the deblurring model and found that it sometimes doesn't work very well on real-world pictures (since trained on synthetic datasets). So I am wondering could you also help create the other three deblurring models we provided [here](https://console.cloud.google.com/storage/browser/gresearch/maxim/ckpt/Deblurring?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false)? I believe it will allow users to have multiple choices to try if one deblurring model doesn't work as expected. Thanks again for your hard work in creating this cool demo!!

**Comment by chenxwh** [comment]
Hi @vztu ,

Glad to hear you like the Replicate demo :) 

I have now added the other three deblurring models to the demo. Let me know if any other changes you'd like. Do claim the [page](https://replicate.com/google-research/maxim) with the button at the top if you are happy with the demo, you can then add additional examples (and change the current ones) ~

We'd also like to encourage you to try out [Cog](https://github.com/replicate/cog) as well, with `cog.yaml` for setting up environment and `predict.py` for inference, then `cog push r8.im/google-research/maxim` (after you are logged in and claimed the ownership for a page) it is easy to update the demo anyway you like :)

**Comment by Yinxiaoli** [comment]
Thanks, Chenxi !

**Comment by zeke** [comment]
Hi @vztu and @Yinxiaoli 👋🏼 

I'm Zeke from the @replicate team.

This model is so cool! I find the "de-raining" feature especially impressive. ☔ 

I just wanted to let you know that the arXiv.org website now includes a link to your model on Replicate!

See the "Demos" tab at the bottom of the page here: https://arxiv.org/abs/2201.02973

Screen Shot 2022-05-02 at 2 31 21 PM

**Pull request merged**
